src/main/groovy/nebula/plugin/dependencylock/DependencyLockPlugin.groovy, src/test/groovy/nebula/plugin/dependencylock/DependencyLockLauncherSpec.groovy
The global lock support currently ignores all resolution strategy forces. This fixes that by adding the generated detached configuration to each project, triggering any configured resolution strategies on that configuration.
=> Fix forcing dependencies on creating a global lock

src/main/groovy/nebula/plugin/dependencylock/DependencyLockPlugin.groovy
Gradle's notation parsing is expensive, because it checks for a plain Dependency first, rather than a string notation, and it uses exceptions for flow control.
This parses the dependencies up front, avoiding parsing the dependencies for each configuration, and calls `force` once with all dependencies to avoid the parser init overhead. It also changes a debug statement to make the `toString` lazy, rather than calling it eagerly.
=> Improve performance of enforcing locks by pre-parsing dependencies

README.md
Tiny fix but it caught me out when trying out the example code. That said, perhaps for the optimal learning experience, I should have re-typed it instead of cut & paste ;-)
=> Fix missing quote from example build file

src/main/groovy/nebula/plugin/dependencylock/DependencyLockPlugin.groovy, src/test/groovy/nebula/plugin/dependencylock/DependencyLockLauncherSpec.groovy
If you go through the trouble of configuring which configurations should be locked on a per-project basis, I'd expect the global lock to use those same configs. This change makes that happen.
=> Use chosen subproject configs in global lock

README.md, src/main/groovy/nebula/plugin/dependencylock/DependencyLockExtension.groovy, src/main/groovy/nebula/plugin/dependencylock/DependencyLockPlugin.groovy, src/test/groovy/nebula/plugin/dependencylock/DependencyLockPluginSpec.groovy
This PR is a follow up to [PR 64](https://github.com/nebula-plugins/gradle-dependency-lock-plugin/pull/64) with a more accurate description and aptly named project property. This PR will hopefully be clearer and not cause confusion by implying that `afterEvaluate` blocks happen at the execution phase.
This does invert the option parameter - default is true and override is false. In any event the default preserves the prior behaviour of the dependency lock plugin.
=> Follow-up to PR-64 with more accurate option name & description.

.travis.yml, build.gradle, src/main/groovy/nebula/plugin/dependencylock/DependencyLockPlugin.groovy, src/main/groovy/nebula/plugin/dependencylock/tasks/GenerateLockTask.groovy, src/test/groovy/nebula/plugin/dependencylock/DependencyLockLauncherSpec.groovy, src/test/groovy/nebula/plugin/dependencylock/DependencyLockPluginIntegrationSpec.groovy
This fixes #95, but also provides a much better guarantees for #86 than the change to `eachDependency` alone provides.
=> Apply locks in beforeResolve by default to ensure that locks are applied at the last possible moment

src/main/groovy/nebula/plugin/dependencylock/tasks/GenerateLockTask.groovy, src/main/groovy/nebula/plugin/dependencylock/tasks/UpdateLockTask.groovy, src/main/kotlin/nebula/plugin/dependencylock/DependencyLockPlugin.kt, src/test/groovy/nebula/plugin/dependencylock/DependencyLockPluginWithCoreSpec.groovy
If you have been using tasks such as `generateLock`, `saveLock`, and `updateLock`, then you can run
```
./gradlew dependencies --write-locks
```
or other tasks to resolve all project configurations (such as those needed for a multi-project build)
and you will be migrated to [core Gradle locks](https://docs.gradle.org/current/userguide/dependency_locking.html).
These are not supported by core Gradle locks. You will need to delete the global lock and use project locks.
=> Migrate to core lock format

src/main/groovy/nebula/plugin/dependencylock/tasks/GenerateLockTask.groovy, src/main/groovy/nebula/plugin/dependencylock/tasks/UpdateLockTask.groovy, src/main/kotlin/nebula/plugin/dependencylock/DependencyLockPlugin.kt, src/test/groovy/nebula/plugin/dependencylock/DependencyLockPluginWithCoreSpec.groovy
Enable migration from Nebula locks to Gradle core locks with '-PmigrateLocks=true' and `coreLockingSupport` enabled
=> Enable migration from Nebula locks to Gradle core locks 

src/main/groovy/nebula/plugin/dependencylock/DependencyLockTaskConfigurer.groovy, src/main/groovy/nebula/plugin/dependencylock/tasks/AbstractMigrateToCoreLocksTask.groovy, src/main/groovy/nebula/plugin/dependencylock/tasks/MigrateLockedDepsToCoreLocksTask.groovy, src/main/groovy/nebula/plugin/dependencylock/tasks/MigrateToCoreLocksTask.groovy, src/test/groovy/nebula/plugin/dependencylock/tasks/MigrateToCoreLocksTaskSpec.groovy
When you run `migrateToCoreLocks`, two tasks are actually run. 
- The first migrates all the locked dependencies from `dependencies.lock` into the core Gradle lock format
- The second finds any dependencies that had not been locked (due to not being added to lock state or not locking transitive dependencies) and locks them in the core Gradle lock format
=> Task migrateToCoreLocks locks previously unlocked dependencies

src/main/groovy/nebula/plugin/dependencylock/ConfigurationsToLockFinder.groovy, src/main/groovy/nebula/plugin/dependencylock/tasks/AbstractMigrateToCoreLocksTask.groovy, src/main/groovy/nebula/plugin/dependencylock/tasks/MigrateLockedDepsToCoreLocksTask.groovy, src/main/groovy/nebula/plugin/dependencylock/tasks/MigrateToCoreLocksTask.groovy, src/main/groovy/nebula/plugin/dependencylock/utils/CoreLockingHelper.groovy, src/main/kotlin/nebula/plugin/dependencylock/DependencyLockPlugin.kt, src/test/groovy/nebula/plugin/dependencylock/DependencyLockPluginWithCoreSpec.groovy, src/test/groovy/nebula/plugin/dependencylock/tasks/MigrateToCoreLocksTaskSpec.groovy
For core Gradle locking: Mark configurations as lockable before the taskGraph resolves
This has the unfortunate side-effect of no longer locking configurations from the facet plugin (such as `smokeTestCompile` or `exampleCompile`), but I'll look into that shortly.
=> Core lock update

src/main/groovy/nebula/plugin/dependencylock/ConfigurationsToLockFinder.groovy, src/main/groovy/nebula/plugin/dependencylock/utils/CoreLockingHelper.groovy, src/test/groovy/nebula/plugin/dependencylock/DependencyLockPluginWithCoreSpec.groovy, src/test/groovy/nebula/plugin/dependencylock/tasks/MigrateToCoreLocksTaskSpec.groovy
to allow versions for plugin configurations to float
Also added a test for a scala project. Scala incremental compilation configurations are non-resolvable and extend from `compile` (resolvable) and `implementation` (non-resolvable) rather than `compileClasspath`. Currently emitting a warning about dependencies listed as `implementation` rather than `compile`
=> Core locking: slim down the configurations to lock by default

build.gradle, dependencies.lock, src/main/groovy/nebula/plugin/dependencylock/ConfigurationsToLockFinder.groovy, src/test/groovy/nebula/plugin/dependencylock/DependencyLockPluginWithCoreSpec.groovy
* lock 'default' configuration in kotlin projects
* add test case for multi-project core locking example
=> Core locking update with examples for multiprojects & kotlin projects

build.gradle, src/main/groovy/nebula/plugin/dependencylock/ConfigurationsToLockFinder.groovy, src/main/groovy/nebula/plugin/dependencylock/utils/CoreLockingHelper.groovy, src/test/groovy/nebula/plugin/dependencylock/DependencyLockPluginWithCoreSpec.groovy, src/test/groovy/nebula/plugin/dependencylock/dependencyfixture/WrapperPlugin.groovy, src/test/groovy/nebula/plugin/dependencylock/tasks/MigrateToCoreLocksTaskSpec.groovy, src/test/resources/META-INF/gradle-plugins/test.wrapper-plugin.properties
* core locks will lock configurations that contribute to `compileClasspath`, `runtimeClasspath`, `annotationProcessor`, and their test- prefix configurations
* core locks can lock additional configurations via property and extension configuration
* core locks can lock custom configurations not added by a plugin
=> Core locks update

src/main/groovy/nebula/plugin/dependencylock/ConfigurationsToLockFinder.groovy, src/test/groovy/nebula/plugin/dependencylock/DependencyLockPluginWithCoreSpec.groovy, src/test/groovy/nebula/plugin/dependencylock/tasks/MigrateToCoreLocksTaskSpec.groovy
It extends the runtime configuration
=> Core locks: lock the 'default' configuration

src/main/groovy/nebula/plugin/dependencylock/utils/CoreLockingHelper.groovy, src/test/groovy/nebula/plugin/dependencylock/DependencyLockPluginWithCoreSpec.groovy
Lock a configuration only once, the first time we see it's supposed to be locked, so that we do not get errors like: 
```
> Cannot change strategy of configuration ':<configurationName>' after it has been resolved.
```
=> Core locking: activate dependency locking for each configuration only once

src/main/groovy/nebula/plugin/dependencylock/DependencyLockExtension.groovy, src/main/groovy/nebula/plugin/dependencylock/DependencyLockTaskConfigurer.groovy, src/main/groovy/nebula/plugin/dependencylock/tasks/GenerateLockTask.groovy, src/test/groovy/nebula/plugin/dependencylock/tasks/GenerateLockTaskSpec.groovy
The idea behind `skippedConfigurationNamesPrefixes` is to allow for skipping configs such as `zinc` and `incrementalAnalysis*`.
The reason for this is that Gradle provides `zinc` compiler which work with specific versions of Scala. 
When the `zinc` configuration is locked and gradle upgrades it, which is the case for 5.x to 6.x where they replaced zinc 0.3.x with modern 1.2.x, the scala version does not work anymore and lock files prevent from a smooth upgrade.
```
Caused by: java.lang.NoSuchMethodError: scala.Product.$init$(Lscala/Product;)V
at scala.xml.NamespaceBinding.<init>(NamespaceBinding.scala:24)
at scala.xml.TopScope$.<init>(TopScope.scala:17)
at scala.xml.TopScope$.<clinit>(TopScope.scala)
at scala.Predef$.<init>(Predef.scala:137)
at scala.Predef$.<clinit>(Predef.scala)
at …
```
=> Introduce skipped configuration names prefixes

src/main/groovy/nebula/plugin/dependencylock/utils/CoreLockingHelper.groovy, src/test/groovy/nebula/plugin/dependencylock/DependencyLockPluginWithCoreSpec.groovy
This will help folks who will be locking fewer configurations. When a plugin update is applied, they can still run build processes without file changes until they are ready to update dependencies.
=> Core lock: ignore extra lockfiles until lock update or regeneration

src/main/groovy/nebula/plugin/dependencylock/DependencyLockTaskConfigurer.groovy, src/test/groovy/nebula/plugin/dependencylock/DependencyLockConfigurationAvoidanceSpec.groovy
First part of task configuration avoidance where the following are broken apart by commits:
- saveLockTask, saveGlobalLockTask
- deleteLockTask, deleteGlobalLockTask
- commitLockTask
- migrateToCoreLocksTask, migrateLockedDepsToCoreLocksTask
=> Task configuration avoidance

src/main/groovy/nebula/plugin/dependencyverifier/DependencyResolutionVerifier.groovy, src/test/groovy/nebula/plugin/dependencyverifier/DependencyResolutionVerifierTest.groovy
Improve error message from DependencyResolutionVerifier for dependencies missing a version by adding a message at the end:
```
The following dependencies are missing a version: group1:artifact1, group2:artifact2
Please add a version to fix this. If you have been using a BOM, perhaps these dependencies are no longer managed
```
=> Improve error message from DependencyResolutionVerifier

src/main/groovy/nebula/plugin/dependencyverifier/DependencyResolutionVerifier.groovy
If the configuration has a resolution alternative, then do not verify that configuration even if it has resolved by something else
=> Skip verifying deprecated configurations

src/main/groovy/nebula/plugin/dependencylock/DependencyLockTaskConfigurer.groovy, src/test/groovy/nebula/plugin/dependencylock/DependencyLockLauncherSpec.groovy
adds spotbugs and scala plugin to the ignored configurations for global lock.
This prevents leaking dependencies from this plugins.
this is a quick fix Since we don't support global locks anymore. Ideally it should only lock configurations that matter
=> add extra configurations for configurationsToSkipForGlobalLock

gradle/wrapper/gradle-wrapper.properties, src/main/groovy/nebula/plugin/dependencylock/ConfigurationsToLockFinder.groovy, src/main/groovy/nebula/plugin/dependencylock/tasks/GenerateLockTask.groovy, src/test/groovy/nebula/plugin/dependencylock/AbstractDependencyLockPluginSpec.groovy, src/test/groovy/nebula/plugin/dependencylock/DependencyLockLauncherSpec.groovy, src/test/groovy/nebula/plugin/dependencylock/DependencyLockPluginWithCoreSpec.groovy, src/test/groovy/nebula/plugin/dependencylock/tasks/DiffLockTaskSpec.groovy, src/test/groovy/nebula/plugin/dependencylock/tasks/GenerateLockTaskSpec.groovy, src/test/groovy/nebula/plugin/dependencylock/util/LockGenerator.groovy, src/test/groovy/nebula/plugin/dependencylock/utils/ConfigurationFiltersProjectSpec.groovy
Part of the work Gradle folks did when we detected the issue with the tooling API metadata is deprecating the `default` configuration which is not resolvable anymore
Here is the PR that addresses that and will be part of Gradle 6.3: https://github.com/gradle/gradle/pull/12460/files
This PR uses a snapshot to make sure things work but I'll update it once RC and/or final comes out
=> default configuration is not resolvable anymore

src/main/groovy/nebula/plugin/dependencylock/DependencyLockReader.groovy, src/main/groovy/nebula/plugin/dependencylock/DependencyLockWriter.groovy, src/main/groovy/nebula/plugin/dependencylock/tasks/GenerateLockTask.groovy, src/main/groovy/nebula/plugin/dependencylock/tasks/MigrateLockedDepsToCoreLocksTask.groovy, src/main/kotlin/nebula/plugin/dependencylock/DependencyLockPlugin.kt, src/test/groovy/nebula/plugin/dependencylock/DependencyLockLauncherSpec.groovy, src/test/groovy/nebula/plugin/dependencylock/DependencyLockPluginSpec.groovy, src/test/groovy/nebula/plugin/dependencylock/DependencyLockPluginWithCoreSpec.groovy, src/test/groovy/nebula/plugin/dependencylock/DependencyLockReaderSpec.groovy, src/test/groovy/nebula/plugin/dependencylock/tasks/DiffLockTaskSpec.groovy, src/test/groovy/nebula/plugin/dependencylock/tasks/GenerateLockTaskSpec.groovy, src/test/groovy/nebula/plugin/dependencylock/tasks/MigrateToCoreLocksTaskSpec.groovy, src/test/groovy/nebula/plugin/dependencylock/tasks/UpdateLockTaskSpec.groovy
Also keep the previous behavior to drop locks for versions without requested versions during a selective dependency update, but this is now done without using the "requested" field in the lock file. (This improves interaction with resolution strategies that affect first order dependencies without versions, like those provided by dependency recommender and Spring dependency management.)
=> Remove 'requested' field from lock files

src/main/kotlin/nebula/plugin/dependencylock/DependencyLockPlugin.kt, src/test/groovy/nebula/plugin/dependencylock/DependencyLockAlignmentLauncherSpec.groovy
Locks are applied with resolutionStrategy.dependencySubstitution.substitute instead of resolutionStrategy.eachDependency with useVersion to assist with core Gradle alignment platform edges
Core Gradle alignment does not apply `useVersion`/`useTarget` to virtual platforms, which make up aligned groups. Instead, this more specific DSL of dependencySubstitution is used and applied to virtual platforms.
For the (admittedly less common) cases where there is a non-locked alignment rule that causes a resolution difference to that seen in the lock file, the resolved version will equal the locked version with Nebula alignment and resolution will fail due to `Multiple forces on different versions for virtual platform` with core Gradle alignment (causing the user to make a change or update their …
=> Locks are applied with a different resolution strategy to assist with core Gradle alignment platform edges

src/main/groovy/nebula/plugin/dependencyverifier/DependencyResolutionVerifierExtension.groovy, src/main/kotlin/nebula/plugin/dependencylock/DependencyLockPlugin.kt, src/main/kotlin/nebula/plugin/dependencyverifier/DependencyResolutionVerifier.kt, src/test/groovy/nebula/plugin/dependencylock/DependencyLockAlignmentLauncherSpec.groovy, src/test/groovy/nebula/plugin/dependencyverifier/DependencyResolutionVerifierTest.groovy
We can use the `DependencyResolutionVerifier` to enforce that resolved versions are the same as locked versions, as using `useVersion`/`useTarget` does not ensure this for aligned dependencies when the project uses core alignment, and using the dependencySubstitution DSL can cause more failures due to “multiple forces for an aligned platform” since an actual substitution rule and a locked version can get into conflict.
As a recap, we switched from `useTarget/useVersion` to the substitution DSL because we saw when migrating from Nebula alignment to core alignment while using Nebula locks, that aligned dependencies have more weight than values found in the lockfile (since `useTarget/useVersion` are not applied to aligned groups). We chose to honor locked versions and fail early for multiple …
=> Verify resolved dependencies use locked version

build.gradle, dependencies.lock
Gradle 6.7.1 is tested through Kotlin 1.4.0 (https://docs.gradle.org/6.7.1/userguide/compatibility.html)
Adding in the kotlinOptions to address the following error:
```
Cannot inline bytecode built with JVM target 1.8 into bytecode that is being built with JVM target 1.6. Please specify proper '-jvm-target' option
```
And adding in related JVM configuration for consistency
=> Use Kotlin 1.4.10 and add explicit Java 1.8 configuration

src/main/groovy/nebula/plugin/dependencylock/utils/ConfigurationFilters.groovy
The resolution alternatives are checked using the private `size` field which may not exist for all potential `List` implementations.
=> Use `size` accessor

src/main/kotlin/nebula/plugin/dependencyverifier/DependencyResolutionVerifier.kt, src/test/groovy/nebula/plugin/dependencyverifier/DependencyResolutionVerifierTest.groovy
DependencyResolutionVerifier does not verify that the resolved version is the locked version when there has been a selective dependency update in the same command (this is currently only run with using core Gradle alignment and Nebula locking).
The information about which locks should be considered for this validation can show a false-positive, such as when `dependencyReport` is run in the same task invocation as `updateDependency`. This is likely related to dependencies from a recommendation BOM or from aligned dependencies. We can disable this additional validation when running selective dependency lock updates to avoid seeing a false positive error.
=> Verifier and selective dependency updates

src/main/groovy/nebula/plugin/dependencylock/DependencyLockTaskConfigurer.groovy, src/test/groovy/nebula/plugin/dependencylock/ResolutionRulesLockabilitySpec.groovy, src/test/groovy/nebula/plugin/dependencylock/util/LockGenerator.groovy
Dependency locking interaction with latest resolution rules plugin. This ensures that the resolution rules configuration can be locked with Nebula project locking, core Gradle locking, and Nebula global locking.
In resolution-rules plugin 9.0.0, the resolution rules configuration was added to each subproject with a project dependency to the root project.
By adding the `resolutionRules` configuration to the set of configurations to skip for each subproject when using global locking, `resolutionRules` remains locked from the parent project and does not run into an error
=> Global locking handles latest resolution rules plugin update

src/main/groovy/nebula/plugin/dependencylock/utils/CoreLockingHelper.groovy, src/main/kotlin/nebula/plugin/dependencylock/DependencyLockPlugin.kt, src/test/groovy/nebula/plugin/dependencylock/DependencyLockLauncherSpec.groovy
This appears to be the only place we're obviously incompatible with configuration caching (`Gradle.buildFinished` and `TaskExecutionGraph.addTaskExecutionListener`).
For the latter, the default since Gradle 7 has been a single lock file per-project, so dangling lock files are no longer a concern. Have I followed that logic correctly?
I'm also out of date on the dependency verifier, so I'll need some background on the problem it solves, but for now I'll just turn it off when configuration caching is enabled so I can get this working for Nebula internally.
=> Remove and flag features incompatible for configuration caching

src/main/groovy/nebula/plugin/dependencylock/DependencyLockExtension.groovy, src/main/kotlin/nebula/plugin/dependencylock/DependencyLockPlugin.kt, src/main/kotlin/nebula/plugin/dependencylock/validation/UpdateDependenciesValidator.kt, src/test/groovy/nebula/plugin/dependencylock/DependencyLockLauncherSpec.groovy, src/test/groovy/nebula/plugin/dependencylock/validation/UpdateDependenciesValidatorSpec.groovy
Setting usage expectations with validations:
- Validation for simultaneous task usage of `updateLock` & `generateLock` which should not be used together
- Validation for requiring specifying dependencies to update when calling `updateLock`
These are both bypass-able default validations with a property or extension.
=> Update dependencies validations

src/main/groovy/nebula/plugin/dependencylock/DependencyLockTaskConfigurer.groovy, src/main/groovy/nebula/plugin/dependencylock/model/ConfigurationResolutionData.groovy, src/main/groovy/nebula/plugin/dependencylock/tasks/GenerateLockTask.groovy, src/test/groovy/nebula/plugin/dependencylock/DependencyLockLauncherSpec.groovy, src/test/groovy/nebula/plugin/dependencylock/ResolutionRulesLockabilitySpec.groovy, src/test/groovy/nebula/plugin/dependencylock/tasks/GenerateLockTaskSpec.groovy, src/test/groovy/nebula/plugin/dependencylock/tasks/UpdateLockTaskSpec.groovy
This is the next step in our journey to configuration cache
* Replaces usages of `Configuration` at task level since it is not supported in configuration cache. Instead this uses `Provider<ResolvedComponentResult>` as suggested in https://docs.gradle.org/current/userguide/configuration_cache.html#config_cache:requirements:disallowed_types
* Introduces a few breaking changes:
* Removes the concept of `includeTransitives` when executing: Because the lazy model is not aware of children and such, it makes more difficult do the sibling navigation. Also, I think this is a decent trade-off: removing complexity in the task and really we want people to always lock all dependencies since locking first level/direct is never enough. 
* The order on which version and `transitive` field is written …
=> GenerateLockTask: use configuration cache compatible APIs

src/main/groovy/nebula/plugin/dependencylock/DependencyLockTaskConfigurer.groovy, src/main/kotlin/nebula/plugin/dependencylock/DependencyLockPlugin.kt, src/test/groovy/nebula/plugin/BaseIntegrationTestKitSpec.groovy, src/test/groovy/nebula/plugin/dependencylock/AbstractDependencyLockPluginSpec.groovy, src/test/groovy/nebula/plugin/dependencylock/DependencyLockAlignmentLauncherSpec.groovy, src/test/groovy/nebula/plugin/dependencylock/DependencyLockConfigurationAvoidanceSpec.groovy, src/test/groovy/nebula/plugin/dependencylock/DependencyLockLauncherSpec.groovy, src/test/groovy/nebula/plugin/dependencylock/DependencyLockPluginIntegrationSpec.groovy, src/test/groovy/nebula/plugin/dependencylock/GlobalLockLauncherSpec.groovy, src/test/groovy/nebula/plugin/dependencylock/PathAwareDependencyDiffSpec.groovy, src/test/groovy/nebula/plugin/dependencylock/ResolutionRulesLockabilitySpec.groovy, src/test/groovy/nebula/plugin/dependencylock/caching/AbstractCachingAndDependencyLockingFeatureFlagsSpec.groovy, src/test/groovy/nebula/plugin/dependencyverifier/DependencyResolutionVerifierTest.groovy
This marks the tasks as not config cache compatible but also introduces usage of the new `BuildFeatures` api. Let's make a major release for this as it requires 8.5+
=> Mark tasks as incompatible with config cache
